version: '3.1'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./SampleCollections:/usr/local/sampleCollections
    working_dir: /usr/local/sampleCollections

  mongo-express:
    image: mongo-express
    ports:
      - 127.0.0.1:8088:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password

  server:
    image: node:7.7.2-alpine
    volumes:
      - ./server:/home/node/app:rw,consistent
    working_dir: /home/node/app
    environment:
      MONGO_USER: root
      MONGO_PASS: password
      MONGO_DBNAME: SampleCollections
      JWT_SECRET: secret
    command: 'npm start'
    ports:
      - 3000:3000